#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

#wclean libso fvDVM
wclean lib fvDVM
wclean
wclean dugksFoam
#wclean dugskFoam

# ----------------------------------------------------------------- end-of-file
